# Generated by Django 3.2.18 on 2023-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter_Detail',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=1000)),
                ('voter_id', models.FileField(null=True, upload_to='documents/', verbose_name='Voter Id')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
    ]
