# Generated by Django 3.2.18 on 2023-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=1000)),
                ('symbol', models.FileField(null=True, upload_to='documents/', verbose_name='Symbol')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
        migrations.AddField(
            model_name='voter_detail',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
